//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCASP.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addresses
    {
        public int AddressID { get; set; }
        public int FamilyID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public byte AddressTypeID { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Plus4 { get; set; }
        public string Country { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<bool> IsCurrent { get; set; }
        public Nullable<bool> IsNoMail { get; set; }
        public Nullable<byte> LabelSettingID { get; set; }
        public string Label { get; set; }
        public string HisLabel { get; set; }
        public string HerLabel { get; set; }
        public Nullable<byte> SalSettingID { get; set; }
        public string Sal { get; set; }
        public string HisSal { get; set; }
        public string HerSal { get; set; }
        public string StreetNo { get; set; }
        public string StreetName { get; set; }
        public string StreetApt { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual AddressTypes AddressTypes { get; set; }
        public virtual Families Families { get; set; }
        public virtual LabelSettings LabelSettings { get; set; }
        public virtual SalSettings SalSettings { get; set; }
    }
}
