//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCASP.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressTypes
    {
        public AddressTypes()
        {
            this.Addresses = new HashSet<Addresses>();
        }
    
        public byte AddressTypeID { get; set; }
        public string AddressType { get; set; }
    
        public virtual ICollection<Addresses> Addresses { get; set; }
    }
}
