//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCASP.Models.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CMSEntities : DbContext
    {
        public CMSEntities()
            : base("name=CMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Addresses> Addresses { get; set; }
        public DbSet<AddressTypes> AddressTypes { get; set; }
        public DbSet<Families> Families { get; set; }
        public DbSet<FamiliesMembers> FamiliesMembers { get; set; }
        public DbSet<LabelSettings> LabelSettings { get; set; }
        public DbSet<LogData> LogData { get; set; }
        public DbSet<LogTransactions> LogTransactions { get; set; }
        public DbSet<Members> Members { get; set; }
        public DbSet<PhoneNumbers> PhoneNumbers { get; set; }
        public DbSet<PhoneTypes> PhoneTypes { get; set; }
        public DbSet<Relations> Relations { get; set; }
        public DbSet<SalSettings> SalSettings { get; set; }
        public DbSet<Tables> Tables { get; set; }
        public DbSet<Settings> Settings { get; set; }
    }
}
