//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCASP.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Families
    {
        public Families()
        {
            this.Addresses = new HashSet<Addresses>();
            this.FamiliesMembers = new HashSet<FamiliesMembers>();
            this.PhoneNumbers = new HashSet<PhoneNumbers>();
        }
    
        public int FamilyID { get; set; }
        public string FiledAs { get; set; }
        public Nullable<bool> IsPrivate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Anniversary { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public bool AfterDark { get; set; }
    
        public virtual ICollection<Addresses> Addresses { get; set; }
        public virtual ICollection<FamiliesMembers> FamiliesMembers { get; set; }
        public virtual ICollection<PhoneNumbers> PhoneNumbers { get; set; }
    }
}
