//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCASP.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamiliesMembers
    {
        public int FamilyID { get; set; }
        public int MemberID { get; set; }
        public byte TypeID { get; set; }
        public Nullable<byte> RelationID { get; set; }
        public string HisHer { get; set; }
        public bool IsDefaultFamily { get; set; }
    
        public virtual Families Families { get; set; }
        public virtual Members Members { get; set; }
    }
}
