//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCASP.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogData
    {
        public int LogID { get; set; }
        public short TableID { get; set; }
        public byte LogType { get; set; }
        public int ID { get; set; }
        public int LogTransactionID { get; set; }
        public System.DateTime LogDate { get; set; }
    }
}
