//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCASP.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTransactions
    {
        public int LogTransactionID { get; set; }
        public System.DateTime LogTransactionDate { get; set; }
        public bool CMS { get; set; }
    }
}
