//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCASP.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public Members()
        {
            this.FamiliesMembers = new HashSet<FamiliesMembers>();
            this.PhoneNumbers = new HashSet<PhoneNumbers>();
        }
    
        public int MemberID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public bool AfterDark { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual ICollection<FamiliesMembers> FamiliesMembers { get; set; }
        public virtual ICollection<PhoneNumbers> PhoneNumbers { get; set; }
    }
}
