//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCASP.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneNumbers
    {
        public int PhoneID { get; set; }
        public int FamilyID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public byte PhoneTypeID { get; set; }
        public string PhoneNumber { get; set; }
        public string PhoneExt { get; set; }
        public string Note { get; set; }
        public Nullable<bool> NoCall { get; set; }
        public string EmergName { get; set; }
        public string EmergRelation { get; set; }
        public bool IsPrimary { get; set; }
        public byte PhoneTypeCount { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual Families Families { get; set; }
        public virtual Members Members { get; set; }
        public virtual PhoneTypes PhoneTypes { get; set; }
    }
}
