//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMVCASP.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhoneTypes
    {
        public PhoneTypes()
        {
            this.PhoneNumbers = new HashSet<PhoneNumbers>();
        }
    
        public byte PhoneTypeID { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<PhoneNumbers> PhoneNumbers { get; set; }
    }
}
